config/routes.rb
Rails.application.routes.draw do

  root 'application#index'
  get 'welcome' => 'application#welcome', as: :welcome
  get 'all' => 'application#all', as: :all
  get 'custom' => 'application#custom', as: :custom

  get 'clear_session' => 'sessions#clear_session', as: :clear_session
  get 'add_source' => 'sessions#add_source', as: :add_source
  get 'log' => 'sessions#log', as: :log
  get 'share_path' => 'sessions#share', as: :share
  get 'clear_path' => 'sessions#clear', as: :clear
  get 'add_trello_story/:id' => 'sessions#add_trello_story', as: :add_trello_story
  match 'trello' => 'sessions#trello', via: [:get, :post], as: :trello

  match "feedback" => "application#feedback", via: [:get, :post], as: :feedback

  get '/:session' => 'application#index'

end

app/models/cloudinary_image.rb
class CloudinaryImage < ActiveRecord::Base
  def self.current_graph_url
    find_by_identifier('graph').url if count > 0
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :url
  validates_uniqueness_of :url
  validates_format_of :url, with: /http(s)*:\/\//, on: :create

  before_save :truncate_title,
              :remove_content_tag,
              :remove_utm_parameters

  before_create :prevent_duplicates

  def truncate_title
    self.title = self.title[0..140] + '...' if self.title && self.title.length > 140
  end

  def prevent_duplicates
    Item.where('created_at >= ?', Time.zone.now - 1.days).each do |item|
      return false if Jaccard.coefficient(title_list, item.title_list) > 0.8
    end
  end

  def remove_content_tag
    # if self.title for shoulda is annoying
    self.title = self.title.gsub(/\s*\[[a-zA-Z]+\]$/, '') if self.title
  end

  def remove_utm_parameters
    self.url = self.url.gsub(/(\?|&)utm[^&]*/,'?').gsub('?&', '?').gsub(/\?+/, '?')
  end

  def title_list
    title.gsub(/\W+/, ' ').downcase.strip.split(' ')
  end

  def reading_time
    self.word_count.to_i / 300
  end

  def format
    return 'pdf' if self.url.match(/\.pdf$/)
    return 'img' if self.url.match(/(\.png$|\.jpg$|\.gif$)/)
  end

  def reading_kind
    url.match(/youtube|youtu\.be/)? 'watch' : 'read'
  end

  def self.matching(sources = ['hacker_news', 'reddit', 'product_hunt'])
    where(source: sources).
      limit(150).
      order(created_at: 'DESC')
  end

  def self.default
    all.order(created_at: 'DESC').limit(300)
  end

  def self.average_hour_count(sources)
    where(source: sources).
      where('created_at >= ?', Time.zone.now - 1.days).
      size / 24
  end
end

app/models/session.rb
class Session < ActiveRecord::Base
  serialize :sources, Array
  serialize :saved_items, Array
  validates_uniqueness_of :identifier
  before_save do
    self.identifier = RandomUsername.username if self.identifier.blank?
  end

  def update_sources(source)
    sources.include?(source)? sources.delete(source) : sources << source
    save
  end

  def self.find_or_create(identifier)
    find_by_identifier(identifier) || create(identifier: identifier)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Notifier

  def index
    return render json: Item.matching if params[:format] == 'json'
    return redirect_to welcome_path unless cookies.permanent[:welcomed]

    if params[:session]
      flash[:message] = 'Session synced!</a>' unless flash[:message]
      @session = get_session(params[:session])
    else
      @session = get_session
    end

    @items = Item.matching
    render :index
  end

  def welcome
    cookies.permanent[:welcomed] = true
    @session = get_session
  end

  def feedback
    unless params[:feedback].blank?
      send_feedback(params[:feedback][:comment], request.env['HTTP_USER_AGENT'])
      flash[:message] = 'Feedback Sent!'
      return redirect_to root_path
    end
  end

  def all
    return render json: Item.default if params[:format] == 'json'
    return redirect_to welcome_path unless cookies.permanent[:welcomed]
    @items = Item.default
    @session = get_session
    render :index
  end

  def custom
    return redirect_to welcome_path unless cookies.permanent[:welcomed]
    @session = get_session
    @items = Item.matching(@session.sources)
    render :index
  end

  def get_session(param = cookies.permanent[:session] || params[:session])
    Session.find_or_create(param).tap do |session|
      cookies.permanent[:session] = session.identifier
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def clear_session
    cookies.permanent[:session] = nil
    cookies.permanent[:welcome] = nil
    flash[:message] = 'All cookies cleared.'
    redirect_to welcome_path
  end

  def log
    session = get_session
    session.update_attribute(:completed_to, params[:time])
    return redirect_to :back
  end

  def add_source
    return redirect_to :back unless SOURCES.include?(params[:source])
    get_session.update_sources(params[:source])
    return redirect_to :back
  end

  def share
    session = get_session
    path = root_path + session.identifier
    flash[:message] = "Visit <a href=\"#{path}\">this link</a> on other devices to sync your read status &amp; settings"
    redirect_to path
  end

  def add_trello_story
    item = Item.find(params[:id])
    session = get_session
    TrelloClient.new(session.trello_token, session.trello_username).add_item(
      title: item.title,
      description: [
        item.url,
        ((item.comment_url?)? "Comments:\n#{item.comment_url}" : ''),
        "via #{item.source.humanize.capitalize}",
        "Saved: #{Time.zone.now} - Posted: #{item.created_at}"
      ].join("\n\n")
    )
    session.update_attribute(:saved_items, session.saved_items + [item.id])
    return redirect_to location_path(request.env["HTTP_REFERER"], item)
  end

  def trello
    if params[:token] && params[:token].length == 64
      get_session.update_attribute(:trello_token, params[:token])
      tc = TrelloClient.new(params[:token])
      get_session.update_attribute(:trello_username, tc.fetch_username)
      tc.add_item({title: 'Welcome to serializer on Trello!'})
    elsif params[:token]
      flash[:message] = 'Please check that token.'
    end
    @session = get_session
  end

  private
    def location_path(referer, item)
      path = (referer)? referer : all_path
      path = path[0..path.index('#')-1] if path.include?('#')
      "#{path}/##{item.id}".gsub(/\/+/, '/')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_ago(time)
    (distance_of_time_in_words(time, Time.new) + ' ago').
      gsub('about', '').
      gsub('hours', 'hrs').
      gsub('minutes', 'mins').
      gsub('less than a', '1').
      strip
  end

  def print_url(url, limit=100)
    begin
      url = url.split('/')[2].
        gsub('www.', '').
        gsub(/\?.*$/, '')
      return url[0..limit] + '...' if url.length > limit
    rescue
      return url
    end
    url
  end
end

app/views/application/_menu.html.slim
-if params[:action] == 'all'
  -sources = SOURCES
-elsif params[:action] == 'index'
  -sources = ['hacker_news', 'reddit', 'product_hunt']
-else
  -sources = current_session.sources
.menu
  .logo
    =link_to 'serializer.io', root_path, class: 'menu-text'
  -unless params[:action] == 'welcome'
    .options
      p
        -[['index', 'home', root_path], ['custom', 'custom', custom_path], ['all', 'all', all_path]].each do |item|
          -if params[:action] == item[0]
            span
              strong =link_to item[1], item[2]
          -else
            span =link_to item[1], item[2]
      p
        span =link_to 'session', share_path, title: 'Link to copy and access your session on other devices'
        span =link_to 'clear', clear_session_path, title: 'Click for a fresh session'
    p.stats
      strong =Item.average_hour_count(sources)
      |&nbsp;items per hour
    p.extras
      -if false #disable button temporarily
        -if current_session.trello_token
          =link_to 'readling list', 'http://trello.com', target: '_blank'
        -else
          =link_to 'readling list', trello_path
      =link_to 'feedback?', feedback_path

app/views/application/_source_selection.html.slim
.source-selector
  -SOURCES.each do |source|
    =link_to(add_source_path(source: source)) do
      -if sources.include?(source)
        =cl_image_tag(source, cloud_name: ENV['CLOUD_NAME'], html_height: '30', html_width: '30', class: 'icon')
      -else
        =cl_image_tag(source, cloud_name: ENV['CLOUD_NAME'], html_height: '30', html_width: '30', class: 'icon unselected')

app/views/application/feedback.html.slim
div.container
  p
    |Not sure what all this is about? Take another look at the&nbsp;
    =link_to 'welcome page', welcome_path, class: 'welcome-link'
    |&nbsp;first.

  =form_tag(feedback_path, method: 'post') do
    =text_area(:feedback, :comment, cols: 40, rows: 15, class: 'comment-box')
    br
    div.submit-area
      =submit_tag('Send', class: 'submit')
  p.tweet
    a.twitter-mention-button data-size=("large") href=("https://twitter.com/intent/tweet?screen_name=charlieegan3&text=serializer%20needs...")
      |Tweet to @charlieegan3
    javascript:
      window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));

app/views/application/index.html.slim
=render 'menu', current_session: @session

-if params[:action] == 'custom'
  =render 'source_selection', sources: @session.sources

-if !@items.empty? && @session && (!@session.completed_to || @items.first.created_at > @session.completed_to)
  =link_to(log_path(time: @items.first.created_at + 1), class: 'log-button') do
    span.tick &#10003;&nbsp;
    span.message Mark all as read

table.item-list
  -displayed_log = false
  -overflow = 20
  -@items.each_with_index do |item, index|
    -overflow -= 1 if displayed_log == true
    -break if overflow == 0
    -if @session && @session.completed_to && displayed_log == false && item.created_at <= @session.completed_to
      -displayed_log = true
      tr
        td.log colspan=(2)
          -if index == 0
            |&#10003; All up-to-date
          -else
            span &#10003;&nbsp;
            |Read to here -&nbsp;
            =distance_of_time_in_words(Time.new, @session.completed_to) + ' ago'
    tr class=('read' if displayed_log) style=("opacity: #{(overflow.to_f / 20)}")
      td
        =link_to(item.url, target: '_blank') do
          =cl_image_tag(item.source, cloud_name: ENV['CLOUD_NAME'], html_height: '20', html_width: '20', class: 'icon')
      td
        =link_to item.title, item.url, class: 'title-link', id: item.id
        span.domain =" (#{print_url(item.url)})"
        span.short-domain =" (#{print_url(item.url, 20)})"
        -if item.format
          span.format-icon =item.format
        br
        span.muted
          =time_ago(item.created_at)
          -if item.reading_time.between?(1,3)
            span.fast ="#{item.reading_time} min #{item.reading_kind}"
          -elsif item.reading_time.between?(4,10)
            span.medium ="#{item.reading_time} min #{item.reading_kind}"
          -elsif item.reading_time.between?(11,100)
            span.slow ="#{item.reading_time} min #{item.reading_kind}"
          -if item.comment_url?
            span =link_to 'comments', item.comment_url
          -if @session.trello_token && @session.saved_items && !@session.saved_items.include?(item.id)
            span =link_to 'save', add_trello_story_path(id: item.id)
          -if item.reading_kind == 'read'
            span =link_to 'points', "http://pointsapp.co/?url=#{item.url}", target: '_blank'
          -if item.tweet_count.to_i > 0
            span =cl_image_tag('twitter', cloud_name: ENV['CLOUD_NAME'], height: '15', width: '15', class: 'twitter-icon')
            span =item.tweet_count
          -if item.topped
            span.topped title=('Reached the top spot!')
              |&#9733;
.graph
  =image_tag(CloudinaryImage.current_graph_url)
  p Post Volume Trend (30hr)

app/views/application/welcome.html.slim
=render 'menu', current_session: @session

div.container
  p.lead
    span.inline-logo serializer
    |&nbsp;collects links from&nbsp;
    =link_to('https://news.ycombinator.com', target: '_blank') do
      =cl_image_tag('hacker_news', cloud_name: ENV['CLOUD_NAME'], html_height: '20', html_width: '20', class: 'inline icon')
    |,&nbsp;
    =link_to('http://www.reddit.com/r/programming/', target: '_blank') do
      =cl_image_tag('reddit', cloud_name: ENV['CLOUD_NAME'], html_height: '20', html_width: '20', class: 'inline icon')
    |&nbsp;&amp;&nbsp;
    =link_to('http://producthunt.com', target: '_blank') do
      =cl_image_tag('product_hunt', cloud_name: ENV['CLOUD_NAME'], html_height: '20', html_width: '20', class: 'inline icon')
    |&nbsp;and lists them in&nbsp;
    em sequential order.

  div.feed
    =link_to(root_path, class: 'swap home') do
      -['hacker_news', 'product_hunt', 'reddit'].each do |source|
        =cl_image_tag(source,  cloud_name: ENV['CLOUD_NAME'],html_height: '20', html_width: '20', class: 'icon source-icon')
  div.feed
    =link_to(all_path, class: 'swap all')
      -SOURCES.each do |source|
        =cl_image_tag(source,  cloud_name: ENV['CLOUD_NAME'],html_height: '20', html_width: '20', class: 'icon source-icon')
  div.feed
    |...or choose your own:
    div =link_to 'custom', custom_path

  div.about
    h1 Syncing & Cookies
    p You can sync read status across devices by visiting your session's path on other devices. Your session path is:
    p.share-path =link_to root_path + @session.identifier, root_path + @session.identifier
    p Visiting that link will set a cookie linking that device to the same shared session. No passwords needed.

    h1 About
    p
      em serializer
      |&nbsp;is just a side project, I wanted a feed for social news sites and I enjoy marking things as read.
    p
      |I was inspired by&nbsp;
      =link_to 'a blog post', 'http://www.slashie.org/articles/shipping-side-projects/'
      |&nbsp;(I assume shared on HN) to make this more than just a quick 'tool' for my personal use.
    p I follow the 'all' list but I made 'home' and 'custom' to let others choose different sources.
    br
    p.muted
      |Built with rails, nokogiri, feedjira, slim, httpclient, random_username, gruff &amp; cloudinary
    p.muted
      |Built by&nbsp;
      =link_to 'Charlie', 'http://www.charlieegan3.com'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>serializer</title>
    <meta name="viewport" content="initial-scale=1">
    <meta name="description" content="Combines various non-linear news sources such as Hacker News and Reddit into a single sequential feed.">
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <% if flash[:message]%>
      <p class="flash"><%= flash[:message].html_safe %></p>
    <% end %>
    <%= yield %>
    <style type="text/css">@import url(http://fonts.googleapis.com/css?family=VT323);</style>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-60492660-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>